# ******************************************************************************************************************
# *                                                                                                                *
# *  Project: Migration Project                                                                                    *
# *                                                                                                                *
# *  Copyright © 2022 MongoExpUser. All Rights Reserved.                                                           *
# *                                                                                                                *
# *                                                                                                                *
# ******************************************************************************************************************


name: CI - MariaDB Migration

on:
  push:
    branches:
    - main
  pull_request:
  # matches pull request for all branches and tag name
    
defaults:
  run:
    shell: bash
  env:
    APPLY: 'no'
    DESTROY: 'no'
    INIT: 'yes'
    PLAN: 'yes'
    VALIDATE: 'no'

jobs:
  start:
    name: start
    environment: start-stop
    concurrency: start-stop
    runs-on: ubuntu-latest
    needs: []
    if: ${{ (github.ref == 'refs/heads/main')  && (github.event_name == 'push') }}
    steps:
    - name: Start Deployment
      run: echo "Starting Deployment of RDS MariaDB.".

  dev-deploy:
    name: dev-deploy
    environment: development
    concurrency: development
    runs-on: ubuntu-latest
    needs: [start]
    if: ${{ (github.ref == 'refs/heads/main')  && (github.event_name == 'push') }}
    steps:
    - name: GitHub Actions Runner Set-up
      uses: actions/checkout@v2
    #- name: Terraform Repo Security Scan Set-up
    #  uses: triat/terraform-security-scan@v3
    - name: Terraform CLI Set-up
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      if: ${{ env.INIT == 'yes' }}
      run: terraform init
    - name: Terraform Validate
      if: ${{ env.VALIDATE == 'yes' }}
      run: terraform validate
    - name: Terraform Variables
      if: ${{ env.PLAN == 'yes' }} || ${{ env.APPLY == 'yes' }}
      run: |-
        cat dev.auto.tfvars <<EOF
        EOF
    - name: Terraform Plan
      if: ${{ env.PLAN == 'yes' }}
      run: terraform plan
    - name: Terraform Apply
      if: ${{ env.APPLY == 'yes' }}
      run: terraform apply -var-file=dev.auto.tfvars -auto-approve
    - name: Terraform Destroy
      if: ${{ env.DESTROY == 'yes' }}
      run: terraform destroy -auto-approve
