name: CI - AWS-TS-CDK Migration

on:
  push:
    branches:
    - main
  pull_request:
   # matches pull request for all branches and tag names

jobs:
  aws-ts-cdk:
    name: AWS-TypeScript-CDK
    runs-on: ubuntu-latest
    env:
      DEV: 'no'
      PROD: 'no'
      PLAN: 'no'
      APPLY: 'no'
      DESTROY: 'yes'
      CDK_INIT_DIRECTORY: 'init'
      BASE_DIRECTORY: '/home/runner/work'
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
    
    - name: Set Up Node.js 17.0.1
      uses: actions/setup-node@v2
      with:
        node-version: 17.0.1

    - name: Install All Dependencies and CDK
      run: |
        sudo apt-get install npm
        sudo npm install -g npm
        sudo npm install -g aws-cdk
        sudo npm install @types/node
        # check versions
        sudo node -v
        sudo npm -v
        # check CWD
        pwd
        sudo mkdir $CDK_INIT_DIRECTORY
        cd $CDK_INIT_DIRECTORY
        sudo cdk init app --language typescript
        # install aws-sdk (globally) and basic services for current project (locally)
        sudo npm install -g aws-cdk
        sudo npm install @aws-cdk/core @aws-cdk/aws-rds @aws-cdk/aws-secretsmanager @aws-cdk/aws-iam
        sudo npm install @aws-cdk/aws-ec2 @aws-cdk/aws-s3 cdk-dynamo-table-viewer  @aws-cdk/aws-dynamodb
        # sudo npm install @aws-cdk/aws-lambda @aws-cdk/aws-apigateway @aws-cdk/aws-ecs-patterns
        # sudo npm install @aws-cdk/aws-events @aws-cdk/aws-sns @aws-cdk/aws-sqs @aws-cdk/aws-sns-subscriptions

    - name: Copy Files to Init Directory & List - Dev
      if: ${{ env.DEV == 'yes' }}
      run: |
        sudo scp -r $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/index-dev.js $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/$CDKTF_INIT_DIRECTORY/index.js
        cd ./$CDK_INIT_DIRECTORY
        pwd
        df -m
        free -m
        ls -l
        
    - name: Copy Files to Init Directory & List - Prod
      if: ${{ env.PROD == 'yes' }}
      run: |
        run: |
        sudo scp -r $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/index-prod.js $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/$CDKTF_INIT_DIRECTORY/index.js
        cd ./$CDK_INIT_DIRECTORY
        pwd
        df -m
        free -m
        ls -l
        
    - name: AWD CDK Plan
      if:  (env.PLAN == 'yes') && ( env.DEV == 'yes' || env.PROD == 'yes' )
      run: sudo cdk synth --app "npx ts-node index.ts"
      
    - name: AWD CDK Difference
      if:  (env.DIFF == 'yes') && ( env.DEV == 'yes' || env.PROD == 'yes' )
      run: sudo cdk diff --app "npx ts-node index.ts"
      
    - name: AWD CDK Apply - Dev
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' && env.APPLY == 'yes' && env.DEV == 'yes'
      run: sudo cdk deploy --app "npx ts-node index.ts"
    
    - name: AWD CDK Apply - Prod
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' && env.APPLY == 'yes' && env.PROD == 'yes'
      run: sudo cdk deploy --app "npx ts-node index.ts"
  
    - name: AWD CDK Destroy
      if: ${{ env.DESTROY == 'yes' }}
      run: sudo cdk destroy --app "npx ts-node index.ts"
