name: CI - AWS-TS-CDK Migration

on:
  push:
    branches:
    - main
  pull_request:
   # matches pull request for all branches and tag names

jobs:
  aws-ts-cdk:
    name: AWS-TypeScript-CDK
    runs-on: ubuntu-latest
    env:
      DEV: 'yes'
      PROD: 'no'
      PLAN: 'no'
      DIFF: 'no'
      APPLY: 'no'
      DESTROY: 'no' 
      CDK_INIT_DIRECTORY: 'init'
      BASE_DIRECTORY: '/home/runner/work'
      REPO_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: actions/checkout@v2
      # note: checkout directory: /home/runner/work/${repo-name}/$${repo-name}
    
    - name: Set Up Node.js 16.3.0
      uses: actions/setup-node@v2
      with:
        node-version: 16.3.0

    - name: Install All Dependencies and CDK
      run: |
        sudo apt-get install npm
        sudo npm install -g npm
        sudo npm install -g typescript
        sudo npm install -g aws-cdk
        sudo npm install -g ts-node
        # check versions
        sudo node -v
        sudo npm -v
        # check CWD
        pwd
        sudo mkdir $CDK_INIT_DIRECTORY
        cd $CDK_INIT_DIRECTORY
        sudo cdk init app --language typescript
        # install basic services for current project (locally)
        #sudo npm install aws-cdk
        #sudo npm install npm
        #sudo npm install typescript
        #sudo npm install aws-cdk
        #sudo npm install ts-node
        sudo npm install @types/node
        sudo npm install @aws-cdk/core 
        sudo npm install @aws-cdk/aws-rds 
        sudo npm install @aws-cdk/aws-secretsmanager 
        sudo npm install @aws-cdk/aws-iam
        sudo npm install @aws-cdk/aws-ec2 
        sudo npm install @aws-cdk/aws-s3 
        sudo npm install cdk-dynamo-table-viewer 
        sudo npm install @aws-cdk/aws-dynamodb
        sudo npm install @aws-cdk/aws-lambda 
        sudo npm install @aws-cdk/aws-apigateway 
        sudo npm install @aws-cdk/aws-ecs-patterns
        sudo npm install @aws-cdk/aws-events 
        sudo npm install @aws-cdk/aws-sns 
        sudo npm install @aws-cdk/aws-sqs 
        sudo npm install @aws-cdk/aws-sns-subscriptions

    - name: Copy Files to Init Directory & List - Dev
      if: ${{ env.DEV == 'yes' }}
      run: |
        sudo scp -r $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/index-dev.ts $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/$CDK_INIT_DIRECTORY/index.ts
        cd ./$CDK_INIT_DIRECTORY
        pwd
        df -m
        free -m
        ls -l
        sudo scp -r $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/index-prod.ts $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/$CDK_INIT_DIRECTORY/index.ts
        sudo cdk synth --app "npx ts-node index.ts"
        
    - name: Copy Files to Init Directory & List - Prod
      if: ${{ env.PROD == 'yes' }}
      run: |
        run: |
        sudo scp -r $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/index-prod.ts $BASE_DIRECTORY/$REPO_NAME/$REPO_NAME/$CDK_INIT_DIRECTORY/index.ts
        cd ./$CDK_INIT_DIRECTORY
        pwd
        df -m
        free -m
        ls -l
        
    - name: AWD CDK Plan
      if:  (env.PLAN == 'yes') && ( env.DEV == 'yes' || env.PROD == 'yes' )
      run: |
        #cd ./$CDK_INIT_DIRECTORY
        sudo cdk synth --app "npx ts-node index.ts"
      
    - name: AWD CDK Difference
      if:  (env.DIFF == 'yes') && ( env.DEV == 'yes' || env.PROD == 'yes' )
      run: |
        #cd ./$CDK_INIT_DIRECTORY
        run: sudo cdk diff --app "npx ts-node index.ts"
      
    - name: AWD CDK Apply - Dev
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' && env.APPLY == 'yes' && env.DEV == 'yes'
      run: |
        #cd ./$CDK_INIT_DIRECTORY
        sudo cdk deploy --app "npx ts-node index.ts"
    
    - name: AWD CDK Apply - Prod
      if: github.ref == 'refs/heads/master' && github.event_name == 'push' && env.APPLY == 'yes' && env.PROD == 'yes'
      run: |
        #cd ./$CDK_INIT_DIRECTORY
        sudo cdk deploy --app "npx ts-node index.ts"
  
    - name: AWD CDK Destroy
      if: ${{ env.DESTROY == 'yes' }}
      run: |
        #cd ./$CDK_INIT_DIRECTORY
        sudo cdk destroy --app "npx ts-node index.ts"
